In [1]:
# Question 1
# What's the version of NumPy that you installed?

import numpy as np

np.__version__

'1.21.5'

In [3]:
# Question 2
# Download Data
!wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv -O data/data.csv

--2022-09-07 09:25:42--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
Resolviendo raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.109.133, 185.199.111.133, ...
Conectando con raw.githubusercontent.com (raw.githubusercontent.com)[185.199.110.133]:443... conectado.
Petición HTTP enviada, esperando respuesta... 200 OK
Longitud: 1475504 (1,4M) [text/plain]
Guardando como: “data/data.csv”

data/data.csv       100%[===================>]   1,41M  6,22MB/s    en 0,2s    

2022-09-07 09:25:43 (6,22 MB/s) - “data/data.csv” guardado [1475504/1475504]



In [101]:
# How many records are in the dataset?

import pandas as pd

df = pd.read_csv('data/data.csv')
print(df.info())
print(df.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Make               11914 non-null  object 
 1   Model              11914 non-null  object 
 2   Year               11914 non-null  int64  
 3   Engine Fuel Type   11911 non-null  object 
 4   Engine HP          11845 non-null  float64
 5   Engine Cylinders   11884 non-null  float64
 6   Transmission Type  11914 non-null  object 
 7   Driven_Wheels      11914 non-null  object 
 8   Number of Doors    11908 non-null  float64
 9   Market Category    8172 non-null   object 
 10  Vehicle Size       11914 non-null  object 
 11  Vehicle Style      11914 non-null  object 
 12  highway MPG        11914 non-null  int64  
 13  city mpg           11914 non-null  int64  
 14  Popularity         11914 non-null  int64  
 15  MSRP               11914 non-null  int64  
dtypes: float64(3), int64(5

In [59]:
df.head(3)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350

In [24]:
# Question 3
# Who are the most popular car manufacturers (top-3) according to the dataset?

df.groupby('Make').size().sort_values(ascending=False).head(3)

Make
Chevrolet     1123
Ford           881
Volkswagen     809
dtype: int64

In [45]:
# Question 4
# What's the number of unique Audi car models in the dataset?

audi = df[df['Make']=='Audi']
audi['Model'].nunique()

34

In [55]:
# Question 5
# How many columns in the dataset have missing values?

df.columns[df.isnull().any()].size

5

In [102]:
df.groupby('Engine Cylinders').size().sort_values(ascending=False).head(20)

Engine Cylinders
4.0     4752
6.0     4489
8.0     2031
12.0     230
5.0      225
10.0      68
0.0       56
3.0       30
16.0       3
dtype: int64

In [77]:
df.mode().iloc[0]

Make                         Chevrolet
Model                   Silverado 1500
Year                              2015
Engine Fuel Type      regular unleaded
Engine HP                        200.0
Engine Cylinders                   4.0
Transmission Type            AUTOMATIC
Driven_Wheels        front wheel drive
Number of Doors                    4.0
Market Category              Crossover
Vehicle Size                   Compact
Vehicle Style                    Sedan
highway MPG                         24
city mpg                            17
Popularity                        1385
MSRP                              2000
Name: 0, dtype: object

In [82]:
df['Engine Cylinders'].mode().iloc[0]

0    4.0
Name: Engine Cylinders, dtype: float64

In [108]:
# Question 6
# Find the median value of "Engine Cylinders" column in the dataset.
print(f'Median: ', df['Engine Cylinders'].median())
# Next, calculate the most frequent value of the same "Engine Cylinders".
print(f'Most Frequent: ', df['Engine Cylinders'].mode().iloc[0])
# Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.
df['Engine Cylinders'].fillna(df['Engine Cylinders'].mode().iloc[0], inplace=True)
# Now, calculate the median value of "Engine Cylinders" once again.
print(f'Median after fillna: ',df['Engine Cylinders'].median())

Median:  6.0
Most Frequent:  4.0
Median after fillna:  6.0


In [110]:
df['Engine Cylinders'].isnull().size

11914

In [169]:
# Question 7
# Select all the "Lotus" cars from the dataset.
df_lotus = df[df['Make'] == 'Lotus']
# Select only columns "Engine HP", "Engine Cylinders".
df_lotus_engine = df_lotus[['Engine HP', 'Engine Cylinders']]
# Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).

# Get the underlying NumPy array. Let's call it X.
X = df_lotus_engine.drop_duplicates().to_numpy()
# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
XTX = X@X.T
# Invert XTX.
XTX_invert = np.linalg.inv(XTX)
# Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

print(f'X:          ',X.shape)
print(f'X.T:        ',X.T.shape)
# What's the value of the first element of w?
#w
print(f'X@X.T:      ', XTX.shape)
print(f'XTX_invert: ', XTX_invert.shape)
print(f'(y:         ', y.shape)

np.dot(X.T@XTX_invert,y)

X:           (9, 2)
X.T:         (2, 9)
X@X.T:       (9, 9)
XTX_invert:  (9, 9)
(y:          (9,)


array([-1.52221667e+20,  4.95395959e+18])

In [152]:
X.T

array([[189., 218., 217., 350., 400., 276., 345., 257., 240.],
       [  4.,   4.,   4.,   8.,   6.,   6.,   6.,   4.,   4.]])

In [153]:
XTX_invert

array([[ 4.87854228e+14,  4.87854228e+14, -2.43927114e+14,
        -4.43700836e+02,  0.00000000e+00,  0.00000000e+00,
         9.75708456e+14,  0.00000000e+00, -5.69668096e+13],
       [-1.24321703e+18,  1.21537533e+18,  1.04678949e+18,
         1.19309393e+06,  1.54368015e+18,  1.24322538e+18,
        -2.34615637e+18, -2.88769717e+17, -1.39803086e+18],
       [ 3.10909462e+30, -3.00802229e+30, -2.60616862e+30,
        -2.92378543e+18, -3.80766291e+30, -3.09060098e+30,
         5.80287311e+30,  7.16740439e+29,  3.43144202e+30],
       [-3.76282469e+29,  3.63025500e+29,  3.15826586e+29,
         3.51724729e+17,  4.59903441e+29,  3.73803774e+29,
        -7.01429734e+29, -8.57588282e+28, -4.15227010e+29],
       [ 7.99442796e+17, -7.82411008e+17, -6.77374261e+17,
         2.25179981e+15, -9.88182636e+17, -8.00396110e+17,
         1.50711850e+18,  1.86616235e+17,  8.91413013e+17],
       [ 2.85365708e+26,  3.64589806e+26, -1.90821110e+27,
         2.00247123e+15,  1.18514900e+26,  1.219690